#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PJAPP.Resource", IsApplication=true)]

namespace PJAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int dialogSlideInUp = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialogSlideOutUp = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int rom_navn = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bigButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dropdown = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int forside_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int infoBoxStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int infoTextStyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int medalje16 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menuItemStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sok = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int styleEditText = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int top_logo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int HjelpButton = 2131230724;
			
			// aapt resource value: 0x7f080026
			public const int ReserverButton = 2131230758;
			
			// aapt resource value: 0x7f08000d
			public const int buttonWrap = 2131230733;
			
			// aapt resource value: 0x7f080014
			public const int grupperomButton = 2131230740;
			
			// aapt resource value: 0x7f08000a
			public const int imageView1 = 2131230730;
			
			// aapt resource value: 0x7f08000f
			public const int infoBox = 2131230735;
			
			// aapt resource value: 0x7f080002
			public const int ingenInfo = 2131230722;
			
			// aapt resource value: 0x7f08001c
			public const int linearLayout1 = 2131230748;
			
			// aapt resource value: 0x7f08000e
			public const int loggInnButton = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int loggUtButton = 2131230742;
			
			// aapt resource value: 0x7f080011
			public const int menuBar = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int menuButton = 2131230738;
			
			// aapt resource value: 0x7f08001d
			public const int plasser1 = 2131230749;
			
			// aapt resource value: 0x7f080021
			public const int plasser2 = 2131230753;
			
			// aapt resource value: 0x7f080017
			public const int profilInfo = 2131230743;
			
			// aapt resource value: 0x7f08001e
			public const int prosjektor1 = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int prosjektor2 = 2131230754;
			
			// aapt resource value: 0x7f08001f
			public const int reserver1 = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int reserver2 = 2131230755;
			
			// aapt resource value: 0x7f080020
			public const int reservert1 = 2131230752;
			
			// aapt resource value: 0x7f080024
			public const int reservert2 = 2131230756;
			
			// aapt resource value: 0x7f080003
			public const int romListe1 = 2131230723;
			
			// aapt resource value: 0x7f08001b
			public const int romNavn = 2131230747;
			
			// aapt resource value: 0x7f080025
			public const int romValg = 2131230757;
			
			// aapt resource value: 0x7f080000
			public const int swiperefresh = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int textView1 = 2131230736;
			
			// aapt resource value: 0x7f080001
			public const int toolbar = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int txtDistance = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int txtEmail = 2131230731;
			
			// aapt resource value: 0x7f080029
			public const int txtFag = 2131230761;
			
			// aapt resource value: 0x7f080005
			public const int txtName = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int txtNavn = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int txtPassword = 2131230732;
			
			// aapt resource value: 0x7f080007
			public const int txtRom = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int txtTid = 2131230729;
			
			// aapt resource value: 0x7f080028
			public const int txtVeilederNavn = 2131230760;
			
			// aapt resource value: 0x7f08001a
			public const int userCourse = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int userLoginName = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int userName = 2131230744;
			
			// aapt resource value: 0x7f080015
			public const int veilederButton = 2131230741;
			
			// aapt resource value: 0x7f080027
			public const int veilederView = 2131230759;
			
			// aapt resource value: 0x7f080013
			public const int westerdalsLogo = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int gruppeRom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int gruppeRomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int helpRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mainPage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menuBar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int menuDialog = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int profilSide = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int romDetalj = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int spinnerItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int veileder = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int veilederRow = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int dialog_animation = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
