#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PJAPP.Resource", IsApplication=true)]

namespace PJAPP
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int dialogSlideInUp = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dialogSlideOutUp = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bigButtonStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dropdown = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int forside_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int infoBoxStyle = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int infoTextStyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int medalje16 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menuItemStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sok = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int styleEditText = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int top_logo = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070025
			public const int Whiteboard = 2131165221;
			
			// aapt resource value: 0x7f07001b
			public const int brukerInfo = 2131165211;
			
			// aapt resource value: 0x7f070009
			public const int buttonWrap = 2131165193;
			
			// aapt resource value: 0x7f07001a
			public const int gamificationInfo = 2131165210;
			
			// aapt resource value: 0x7f07000b
			public const int glemtButton = 2131165195;
			
			// aapt resource value: 0x7f070013
			public const int grupperomButton = 2131165203;
			
			// aapt resource value: 0x7f070006
			public const int imageView1 = 2131165190;
			
			// aapt resource value: 0x7f07001e
			public const int imageView2 = 2131165214;
			
			// aapt resource value: 0x7f070021
			public const int imageView3 = 2131165217;
			
			// aapt resource value: 0x7f07000d
			public const int infoBox = 2131165197;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout1 = 2131165208;
			
			// aapt resource value: 0x7f07001c
			public const int linearLayout2 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int linearLayout3 = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int linearLayout4 = 2131165216;
			
			// aapt resource value: 0x7f070000
			public const int listeHeader1 = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int loggInnButton = 2131165194;
			
			// aapt resource value: 0x7f070016
			public const int loggUtButton = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int menuBar = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int menuButton = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int minProfilButton = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int profilBilde = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int profilInfo = 2131165207;
			
			// aapt resource value: 0x7f070026
			public const int prosjektor = 2131165222;
			
			// aapt resource value: 0x7f070001
			public const int romListe1 = 2131165185;
			
			// aapt resource value: 0x7f070023
			public const int romNavn = 2131165219;
			
			// aapt resource value: 0x7f070012
			public const int searchButton = 2131165202;
			
			// aapt resource value: 0x7f070024
			public const int storrelse = 2131165220;
			
			// aapt resource value: 0x7f07000e
			public const int textView1 = 2131165198;
			
			// aapt resource value: 0x7f07001f
			public const int textView2 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int textView3 = 2131165218;
			
			// aapt resource value: 0x7f07000c
			public const int toolbar = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int txtDistance = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int txtEmail = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int txtMajor = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int txtMinor = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int txtName = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int txtPassword = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int veilederButton = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int westerdalsLogo = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int gruppeRom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int gruppeRomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int mainPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int menuBar = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int menuDialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int profilSide = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int romDetalj = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int veileder = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
